######################################################################
# Automatically generated by qmake (3.0) ?? 3? 16 14:25:47 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = dialog
INCLUDEPATH += .

# Input
HEADERS += sortdialog.h ui_sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
