######################################################################
# Automatically generated by qmake (3.0) ?? 3? 15 19:09:08 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
