######################################################################
# Automatically generated by qmake (3.0) ?? 3? 15 20:51:59 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 2
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp

FORMS +=
