######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 2 09:46:53 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
