######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 3 09:57:43 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += connect.h
SOURCES += connect.cpp main.cpp
