######################################################################
# Automatically generated by qmake (3.0) ?? 3? 15 23:40:08 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 3
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
