######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 2 21:23:02 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += find.h
SOURCES += find.cpp main.cpp
