######################################################################
# Automatically generated by qmake (3.0) ?? 3? 15 23:32:37 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = ui
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
