######################################################################
# Automatically generated by qmake (3.0) ?? 3? 14 22:33:21 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 12
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += res.qrc
