######################################################################
# Automatically generated by qmake (3.0) ?? 3? 15 14:44:13 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 13
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
