######################################################################
# Automatically generated by qmake (3.0) ?? 12? 27 16:59:10 2015
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
QT+=widgets
