######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 2 20:36:04 2016
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
